version: '3'
services:
  solr: &solr
    image: mdl_solr:dev
    ports:
      - "8983:8983"
    volumes:
      - ./solr_snapshots:/solr_snapshots
    networks:
      - mdl
  solr_test:
    <<: *solr
    ports:
      - "8986:8983"
  web:
    build: .
    env_file:
      - .env
    command: >
      bash -c "
        RAILS_ENV=test rails s -b 0.0.0.0 -p 3001 --pid `pwd`/tmp/pids/server-test.pid &
        # Run web server
        rails s -b 0.0.0.0 -p 3000"
    ports: ['3000:3000', '3001:3001']
    volumes:
      - .:/app
    links:
      - solr
      - db
      - selenium
    depends_on:
      - solr
  db:
    image: library/mysql:5.7
    env_file:
      - .env
    ports:
      - '3306:3306'
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d/
    networks:
      - mdl
  sidekiq:
    build: .
    command: bundle exec sidekiq -q critical,2 -c 1 -q default -c 2 -r /app
    volumes:
      - .:/app
    links:
      - redis
      - db
    env_file:
      - .env
    networks:
      - mdl
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - mdl
  redis_cache:
    image: redis:4.0.10
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
        - ./docker/redis-cache.conf:/usr/local/etc/redis/redis.conf
    networks:
      - mdl

  webpacker:
      build: .
      command: ./bin/webpack-dev-server
      volumes:
        - .:/app
      ports:
        - '8080:8080'
  selenium:
    image: selenium/standalone-chrome-debug:latest
    ports: ['4444:4444', '5900:5900']
    stdin_open: true
    tty: true
volumes:
  reflections-db-data-mysql-5-7:
    driver: local
  reflections-db-test-data-mysql-5-7:
    driver: local

networks:
  mdl:
